# Site settings
title: WellingtonFamily
email: 
description: > # this means to ignore newlines until "baseurl:"
  A place to call home...
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
#twitter_username: twitter_username
#github_username:  github_username

assets: http://assets.wellingtonfamily.net.s3-website-us-west-2.amazonaws.com/

# Build settings
markdown: kramdown

#highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  tori:
    output: true
    permalink: /tori/:path/

gems: [jekyll-paginate]
