# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

#auto: true # automatically update your jekyll
#server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

timezone: America/Los_Angeles

collections:
  events:
    output: true
    permalink: /:path/
    defaults:
      values:
        layout: event
  
  pages:
    output: true
    permalink: /:path/
    defaults:
      values:
        layout: post_page