# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

#auto: true # automatically update your jekyll
#server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

timezone: America/Los_Angeles

gems:
  - jekyll-paginate

assets: http://assets.wellingtonfamily.net.s3-website-us-west-2.amazonaws.com/

collections:
  events:
    output: true
    permalink: /events/:path/
    defaults:
      values:
        layout: event
  maria:
    output: true
#    permalink: /maria/:path/
    defaults:
      values:
        layout: post_page  
  tori:
    output: true
#    permalink: /tori/:path/
    defaults:
      values:
        layout: post_page  


