# Site settings
title: WellingtonFamily
email:
description: > # this means to ignore newlines until "baseurl:"
  A place to call home...
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
#twitter_username: twitter_username
#github_username:  github_username

assets: http://assets.wellingtonfamily.net.s3-website-us-west-2.amazonaws.com

# Build settings
markdown: kramdown

#highlighter: pygments

# Pagination - turned off for now, not being used
# paginate: 15
# paginate_path: "/blog/page:num/"

plugins: [jekyll-paginate]

collections:
  maria:
    output: true
    permalink: /maria/:path/
  tori:
    output: true
    permalink: /tori/:path/
  geocaching:
    output: true
    permalink: /geocaching/:path/
  cameras:
    output: true
    permalink: /bill/cameras/:path/
  temp:
    output: true
    permalink: /temp/:path/
  knives:
    output: true
    permalink: /bill/knives/:path/
  temp:
    output: true
    permalink: /temp/:path/

defaults:
  - scope:
      path: ""
      type: ""
    values:
      layout: "page"

  - scope:
      path: ""
      type: "cameras"
    values:
      layout: "page"

  - scope:
      path: ""
      type: "knives"
    values:
      layout: "page"

