backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/media/uploads"
public_folder: "/media/uploads"

collections:
    - name: "maria"
      label: "Maria"
      folder: "_maria"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      preview_path: /news/{{slug}}
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Author", name: "author", widget: "string", required: false}

    - name: "victoria"
      label: "Victoria"
      folder: "_victoria"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      preview_path: /news/{{slug}}
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Author", name: "author", widget: "string", required: false}
        - {label: "Body", name: "body", widget: "markdown"}
        - label: "Thumbnail Image (for index page)"
          name: "thumbnail"
          widget: "file"
          default: 
          media_library:
            config:
              multiple: true
          required: false
        - label: "Full Size Image, Video, or other Files"
          name: "linked-file"
          widget: "file"
          default: 
          media_library:
            config:
              multiple: true
          required: false


