backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/media/uploads"
public_folder: "/media/uploads"

collections:
    - name: "maria"
      label: "Maria"
      folder: "_posts"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      preview_path: /news/{{slug}}
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Author", name: "author", widget: "string", required: false}

    - name: "victoria"
      label: "Victoria"
      folder: "_posts"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      preview_path: /news/{{slug}}
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Author", name: "author", widget: "string", required: false}



